baseURL = 'https://mark-z-r.github.io/'
languageCode = 'en-us'
title = "Mark's Website"
disableKinds = ['rss','sitemap']
[taxonomies]
  tags = 'tags'
[minify]
 minifyOutput = false
[markup.goldmark.renderer]
  unsafe = true
